### ISSUE TITLE
Version of level too old to build on Windows 10

### ISSUE THREAD

**Issue by conoro** [johnbrett/hapi-level#1]
Hi John,
I'm trying out your hapi-level-sample project on Windows (thanks!) but it won't build on Windows 10 (with VS 2015) due to the reference to _level_ 0.18.x. That version of _level_ relies on an old node-gyp which is incompatible with Win10/VS2015 (and Win 8.1 I'd guess). I forked your repo and changed package.json to refer to _level_ version 1.3.x. It then builds ok and hapi-level-sample seems to run fine.

Conor

**Comment by johnbrett** [comment]
Hey conor. Will update this. Level had a rewrite after I made that project,
which would corrupt all old databases so was hesitant to update hapi level.
I'll make the upgrade now, and update the hapi level sample project when I
get a chance. If you'd like anything covered in the project let me know as
well!

**Comment by johnbrett** [comment]
Actually, do you want to submit a pull request to hapi level with the
updated version? Can help you with it if you like?

**Comment by conoro** [comment]
Ah I figured there might be some sort of backwards-compatibility concerns alright. PR issued.

Will play more now!
