### ISSUE TITLE
Expose

### ISSUE THREAD

**Issue by simon-p-r** [johnbrett/hapi-level#6]
Hi

I am just wondering whether you will accept a PR for changing how plugin is exposed, the change would be to either decorate the server object or add to server.app namespace.   I normally never use plugin expose method because it is limited to the handler functions and cannot be used globally within hapi.  I would rather contribute to this module than maintain another module.  

Thanks
Simon

**Comment by johnbrett** [comment]
Hi Simon, I would certainly accept a PR - this plugin was actually written before the server.decorate API was released. 

Before you do though, I believe you're incorrect in assuming you can't use something via plugin.expose outside of the handler. Anywhere you have access to your server instance you can use:
````
server.plugins['hapi-level'].db.anyLevelDBMethod();
````
Can you provide a gist where you can't use this as-is, where you could via server.expose? 

We can then look at a PR - and I would likely do this via decoration as opposed to server.app, I usually reserve server.app for global app data, not for exposing database connections etc.

**Comment by simon-p-r** [comment]
Ah your right, maybe I don't use that method as it involves more typing.  I will make a PR up and see what you think.

Thanks Simon
